### ISSUE TITLE
Help please, I have some problems when I try to integrate Receigen code into my project.

### ISSUE THREAD

**Issue by leontea** [letiemble/ReceiptQuickLook#2]
Hi, Laurent, 

I've read the integration guide on your website, and I read this:
![06a398b440c15374bbb7a6ae4c6b71f5](https://user-images.githubusercontent.com/16315287/69219788-8f9f0580-0bae-11ea-89af-f59538ab7c0e.png)

However, when I try to integrate this code to my projects, I got this warning:
![66d2d56f0b9adc4aaa72cf1d69c6bfe0](https://user-images.githubusercontent.com/16315287/69219805-962d7d00-0bae-11ea-9f3d-d5d9d062c01a.png)

When I run my app, it failed:
![a86d7c3ca7607a82ef8f0e9e48ddd46a](https://user-images.githubusercontent.com/16315287/69219809-988fd700-0bae-11ea-8ff1-49568f71dd9e.png)

I have imported the header file, and as you can see, the macro CS_INAPP_QUANTITY can be recognized correctly.

Where did I go wrong?

**Comment by letiemble** [comment]
I close the issue as it is not related to the project.
