### ISSUE TITLE
MacOS Catalina

### ISSUE THREAD

**Issue by ddaddy** [letiemble/ReceiptQuickLook#3]
I've just updated to MacOS Catalina and now get this popup error

`“ReceiptQuickLook.qlgenerator” can’t be opened because Apple cannot check it for malicious software.`

I installed using brew. I've tried to build it myself but it seems the Podfile is wrong and so is the Podfile of `OpenSSL-LET`

Do yo know a way to get this working on Catalina?

**Comment by ddaddy** [comment]
I know this is a very old project, but it still works great.
I have updated the podfile to work with the latest CocoaPods.
If you build this yourself in Xcode and sign it with your own dev certificate it works perfectly in macOS Catalina.

Thanks

**Comment by letiemble** [comment]
PR merged.
